name: Deploy Manual para EC2

on:
  workflow_dispatch:  # Permite executar o deploy manualmente pelo GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Criar chave PEM
      run: |
        echo "${{ secrets.EC2_KEY }}" > key.pem
        chmod 400 key.pem

    - name: Compilar aplicação (Maven)
      run: mvn clean package -DskipTests

    - name: Copiar JAR para EC2
      run: |
        scp -o StrictHostKeyChecking=no -i key.pem \
          target/todo-app-spring-0.0.1-SNAPSHOT.jar \
          ubuntu@ec2-18-231-67-244.sa-east-1.compute.amazonaws.com:/home/ubuntu/

    - name: Executar JAR na EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem \
          ubuntu@ec2-18-231-67-244.sa-east-1.compute.amazonaws.com \
          'nohup java -jar /home/ubuntu/todo-app-spring-0.0.1-SNAPSHOT.jar > log.txt 2>&1 &'
